controllers/AlumnosController.php
<?php

namespace app\controllers;

use app\models\Alumnos;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use Yii;
use app\models\User;
use app\models\Telefonos;
use yii\data\SqlDataProvider;

/**
 * AlumnosController implements the CRUD actions for Alumnos model.
 */
class AlumnosController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all Alumnos models.
     *
     * @return string
     */
    public function actionIndex()
    {
        if (!User::canIn(['admin','maestra'])) {
            return $this->redirect('site/login');
        }
        
        $alumnos = new SqlDataProvider([
            'sql' => 'SELECT a.*, t.telefono FROM alumnos a INNER JOIN telefonos t ON a.codigo = t.codigo_alum
            INNER JOIN niveles n ON a.color_nivel = n.color
            INNER JOIN ensenan e ON n.color = e.color_nivel
            WHERE e.codigo_ma="' . Yii::$app->user->identity->id . '"
            GROUP BY a.nombre_y_apellidos'
        ]);


        $dataProvider = new ActiveDataProvider([
            'query' => Alumnos::find(),
            /*
            'pagination' => [
                'pageSize' => 50
            ],
            'sort' => [
                'defaultOrder' => [
                    'codigo' => SORT_DESC,
                ]
            ],
            */
        ]);

        return $this->render('index', [
            'dataProvider' => $alumnos,
        ]);
    }

    /**
     * Displays a single Alumnos model.
     * @param string $codigo Codigo
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($codigo)
    {
        if (Yii::$app->user->isGuest) {
            return $this->redirect('site/login');
        }
        if (User::can('alumna') && $codigo!=Yii::$app->user->identity->id) {
            return $this->redirect('site/index');
        }

        
        $telefonos = new ActiveDataProvider([
           'query' => Telefonos::find()->select("telefono")->where("codigo_alum='" . $codigo . "'") 
        ]);

        $instrumentos = new SqlDataProvider([
            'sql' => 'SELECT i.nombre
            FROM instrumentos i INNER JOIN utilizan u ON i.codigo = u.codigo_ins
            WHERE u.codigo_alum="' . $codigo . '"',
            'sort' => [
                    'attributes' => [
                        'nombre'
                    ]],
        ]);
        
        return $this->render('view', [
            'model' => $this->findModel($codigo),
            'telefonos' => $telefonos,
            'instrumentos' => $instrumentos
        ]);
        
    }

    /**
     * Creates a new Alumnos model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        if (!User::canIn(['admin','maestra'])) {
            return $this->redirect('site/login');
        }
        
        $model = new Alumnos();

        if ($this->request->isPost) {
            if ($model->load($this->request->post()) && $model->save()) {
                return $this->redirect(['view', 'codigo' => $model->codigo]);
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Alumnos model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $codigo Codigo
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($codigo)
    {
        if (Yii::$app->user->isGuest) {
            return $this->redirect('site/login');
        }
        if (User::can('alumna') && $codigo!=Yii::$app->user->identity->id) {
            return $this->redirect('site/index');
        }

        $telefonoModel = Telefonos::from($codigo);
        $telefonos = new ActiveDataProvider([
            'query' => Telefonos::find()->select("*")->where("codigo_alum='" . $codigo . "'")
        ]);
        $model = $this->findModel($codigo);
        
        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['view', 'codigo' => $model->codigo]);
        }
    
        return $this->render('update', [
            'model' => $model,
            'telefonoModel' => $telefonoModel,
            'telefonos' => $telefonos
        ]);
    }

    /**
     * Deletes an existing Alumnos model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $codigo Codigo
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($codigo)
    {
        if (!User::canIn(['admin','maestra'])) {
            return $this->redirect('site/login');
        } 
        
        $this->findModel($codigo)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Alumnos model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $codigo Codigo
     * @return Alumnos the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($codigo)
    {
        if (($model = Alumnos::findOne(['codigo' => $codigo])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
}

controllers/EnsenanController.php
<?php

namespace app\controllers;

use app\models\Ensenan;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\User;
use Yii;

/**
 * EnsenanController implements the CRUD actions for Ensenan model.
 */
class EnsenanController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all Ensenan models.
     *
     * @return string
     */
    public function actionIndex()
    {
        if (!User::can('admin')) {
            return $this->redirect('site/login');
        }
        
        $dataProvider = new ActiveDataProvider([
            'query' => Ensenan::find(),
            /*
            'pagination' => [
                'pageSize' => 50
            ],
            'sort' => [
                'defaultOrder' => [
                    'id' => SORT_DESC,
                ]
            ],
            */
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Ensenan model.
     * @param int $id ID
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        if (!User::canIn(['admin','maestra']) || (User::can('maestra') && $id!=Yii::$app->user->identity->id)) {
            return $this->redirect('site/login');
        }
        
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Ensenan model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        if (!User::can('admin')) {
            return $this->redirect('site/login');
        }
        
        $model = new Ensenan();

        if ($this->request->isPost) {
            if ($model->load($this->request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Ensenan model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $id ID
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        if (!User::canIn(['admin','maestra']) || (User::can('maestra') && $id!=Yii::$app->user->identity->id)) {
            return $this->redirect('site/login');
        }
        
        $model = $this->findModel($id);

        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Ensenan model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $id ID
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        if (!User::can('admin')) {
            return $this->redirect('site/login');
        }
        
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Ensenan model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $id ID
     * @return Ensenan the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Ensenan::findOne(['id' => $id])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
}

controllers/PasosController.php
<?php

namespace app\controllers;

use app\models\Pasos;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\Instrumentos;
use yii\helpers\Json;
use yii\helpers\Url;
use yii\helpers\FileHelper;
use Yii;
use Mpdf\Mpdf;
use app\models\User;
/**
 * PasosController implements the CRUD actions for Pasos model.
 */
class PasosController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all Pasos models.
     *
     * @return string
     */
    public function actionIndex()
    {
        if (Yii::$app->user->isGuest) {
            return $this->redirect('site/login');
        }
        
        $pasos = [];
        $instrumentosQuery = new ActiveDataProvider([
            'query' => Instrumentos::find()
        ]);

        $instrumentos = $instrumentosQuery->getModels();

        foreach($instrumentos as $instrumento) {
            $pasos[$instrumento->codigo] = new ActiveDataProvider([
                'query' => Pasos::find()->select("*")->where("codigo_ins='" . $instrumento->codigo . "'"),
            ]); 
        }
        
        $imagen = '@web/imagenes/IMG_4258.jpg';

        return $this->render('index', [
            'pasos' => $pasos,
            'url'=> $imagen,
            'instrumentos' => $instrumentos
        ]);
    }

    /**
     * Displays a single Pasos model.
     * @param int $codigo Codigo
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($codigo)
    {
        if (Yii::$app->user->isGuest) {
            return $this->redirect('site/login');
        }
        
        return $this->render('view', [
            'model' => $this->findModel($codigo),
        ]);
    }

    /**
     * Creates a new Pasos model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        if (!User::canIn(['admin','maestra'])) {
            return $this->redirect('site/login');
        }
        
        $model = new Pasos();

        if ($this->request->isPost) {
            if ($model->load($this->request->post()) && $model->save()) {
                return $this->redirect(['view', 'codigo' => $model->codigo]);
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Pasos model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $codigo Codigo
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($codigo)
    {
        if (!User::canIn(['admin','maestra'])) {
            return $this->redirect('site/login');
        }
        
        $model = $this->findModel($codigo);

        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['view', 'codigo' => $model->codigo]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Pasos model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $codigo Codigo
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($codigo)
    {
        if (!User::canIn(['admin','maestra'])) {
            return $this->redirect('site/login');
        }
        
        $this->findModel($codigo)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Pasos model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $codigo Codigo
     * @return Pasos the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($codigo)
    {
        if (($model = Pasos::findOne(['codigo' => $codigo])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
    
    public function actionDownloadPdf($id) {
        // Find your model by ID
        $model = Pasos::findOne($id);

        // Check if the model exists
        if ($model === null) {
            throw new \yii\web\NotFoundHttpException('The requested page does not exist.');
        }

        // Generate the PDF content
        $content = $this->renderPartial('_pdf_template', ['model' => $model]); // Use a partial view to render your model data in PDF

        // Setup the PDF
        $pdf = new mPDF();
        $pdf->WriteHTML($content);

        // Output the PDF as a downloadable file
        $pdf->Output('filename.pdf', 'D'); // 'D' sends the file inline to the browser (default), 'F' saves to a file

        // Exit to prevent Yii from rendering any view
        Yii::$app->end();
    }
    
    public function actionQuiz() {
        // Obtenemos todos los pasos usando ActiveDataProvider
        $dataProvider = new ActiveDataProvider([
            'query' => Pasos::find(),
            'pagination' => false, // Deshabilitamos la paginación para obtener todos los registros
        ]);
        
        // Convertimos el ActiveDataProvider a un array de modelos
        $models = $dataProvider->getModels();
        $questions = [];
        $answers = [];
    
        for ($i = 0; $i < 4; $i++) {
            // Selecciona un elemento aleatorio y obtén su modelo
            $itemIndex = array_rand($models);
            $questions[$i][0] = $models[$itemIndex];
            
            // Elimina el elemento seleccionado y reindexa el array
            array_splice($models, $itemIndex, 1);
    
            for ($j = 1; $j < 4; $j++) {
                // Selecciona un elemento aleatorio de los restantes y obtén su modelo
                $itemIndex = array_rand($models);
                $questions[$i][$j] = $models[$itemIndex];
                
                // Elimina el elemento seleccionado y reindexa el array
                array_splice($models, $itemIndex, 1);
            }
    
            // Guarda la respuesta correcta
            $answers[$i] = $questions[$i][0];
            
            // Baraja las respuestas
            shuffle($questions[$i]);
        }
    
        return $this->render('quiz', [
            'questions' => $questions,
            'answers' => $answers
        ]);
    }
    

}

views/site/administracion.php
<?php
use app\models\Maestros;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\ActionColumn;
use yii\grid\GridView;
use yii\widgets\Pjax;
use app\models\Alumnos;
use app\models\Telefonos;
use app\models\Utilizan;
use app\models\Ensenan;
use app\models\Niveles;
use app\models\Pasos;
use app\models\Aprenden;
use app\models\Instrumentos;

/* 
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Scripting/EmptyPHP.php to edit this template
 */
?>
<div class="rows centrar">
<button class="btn btn-primary boton">Alumnas</button>
<button class="btn btn-primary boton">Maestras</button>
<button class="btn btn-primary boton">Pasos</button>
<button class="btn btn-primary boton">Aprenden</button>
<button class="btn btn-primary boton">Enseñan</button>
<button class="btn btn-primary boton">Niveles</button>
<button class="btn btn-primary boton">Teléfonos</button>
<button class="btn btn-primary boton">Utilizan</button>
<button class="btn btn-primary boton">Instrumentos</button>
</div>
    <div id="alumnas-tab" class="tab">
    <div class="d-flex justify-content-center">
        <div class="col-md-4"></div>
        <p class="col-md-1">
            <?= Html::a(Yii::t('app', 'Añadir Alumno'), ['alumnos/create'], ['class' => 'btn btn-success']) ?>
        </p>
        <!-- <div class="col-md-1"></div> -->
        <h1 class="col-md-1">Alumnas</h1>
        <div class="col-md-4"></div>
    </div>
    

    <?php Pjax::begin(); ?>

    <?= GridView::widget([
        'dataProvider' => $alumnos,
        'columns' => [
            // 'codigo',
            'nombre_y_apellidos',
            'fecha_nacimiento',
            'fecha_ingreso',
            'celula',
            'color_nivel',
            [
                'class' => ActionColumn::className(),
                'urlCreator' => function ($action, Alumnos $model, $key, $index, $column) {
                    return Url::toRoute(["alumnos/".$action, 'codigo' => $model->codigo]);
                 }
            ],
        ],
        'summary' => '',
    ]); ?>

    <?php Pjax::end(); ?>

    </div>
    <div id="maestras-tab" class="tab">
    <div class="d-flex justify-content-center">
        <div class="col-md-4"></div>
        <p class="col-md-1">
            <?= Html::a(Yii::t('app', 'Añadir Maestra'), ['maestros/create'], ['class' => 'btn btn-success']) ?>
        </p>
        <!-- <div class="col-md-1"></div> -->
        <h1 class="col-md-1">Maestras</h1>
        <div class="col-md-4"></div>
    </div>
        <?php Pjax::begin(); ?>
        <?= GridView::widget([
            'dataProvider' => $maestros,
            'columns' => [
                // 'codigo',
                'nombre_y_apellidos',
                'fecha_nacimiento',
                'agno_graduacion',
                'celula',
                [
                    'class' => ActionColumn::className(),
                    'urlCreator' => function ($action, Maestros $model, $key, $index, $column) {
                        return Url::toRoute(["maestros/".$action, 'codigo' => $model->codigo]);
                    }
                ],
            ],
            'summary' => '',
        ]); ?>
        <?php Pjax::end(); ?>
    </div>
    <div id="pasos-tab" class="tab">
    <div class="d-flex justify-content-center">
        <div class="col-md-4"></div>
        <p class="col-md-1">
            <?= Html::a(Yii::t('app', 'Añadir Paso'), ['pasos/create'], ['class' => 'btn btn-success']) ?>
        </p>
        <!-- <div class="col-md-1"></div> -->
        <h1 class="col-md-1">Pasos</h1>
        <div class="col-md-4"></div>
    </div>
        <?php Pjax::begin(); ?>
        <?= GridView::widget([
            'dataProvider' => $pasos,
            'columns' => [
                // 'codigo',
                'nombre',
                'cita_biblica',
                'imagen',
                'video',
                'codigo_ins',
                [
                    'class' => ActionColumn::className(),
                    'urlCreator' => function ($action, Pasos $model, $key, $index, $column) {
                        return Url::toRoute(["pasos/".$action, 'codigo' => $model->codigo]);
                    }
                ],
            ],
            'summary' => '',
        ]); ?>
        <?php Pjax::end(); ?>
    </div>
    <div id="aprenden-tab" class="tab">
    <div class="d-flex justify-content-center">
        <div class="col-md-4"></div>
        <p class="col-md-1">
            <?= Html::a(Yii::t('app', 'Añadir Aprenden'), ['aprenden/create'], ['class' => 'btn btn-success']) ?>
        </p>
        <!-- <div class="col-md-1"></div> -->
        <h1 class="col-md-1">Aprenden</h1>
        <div class="col-md-4"></div>
    </div>
        <?php Pjax::begin(); ?>
        <?= GridView::widget([
            'dataProvider' => $aprenden,
            'columns' => [
                // 'id',
                'color_nivel',
                'codigo_pasos',
                [
                    'class' => ActionColumn::className(),
                    'urlCreator' => function ($action, Aprenden $model, $key, $index, $column) {
                        return Url::toRoute(["aprenden/".$action, 'id' => $model->id]);
                    }
                ],
            ],
            'summary' => '',
        ]); ?>
        <?php Pjax::end(); ?>
    </div>
    <div id="ensenan-tab" class="tab">
    <div class="d-flex justify-content-center">
        <div class="col-md-4"></div>
        <p class="col-md-1">
            <?= Html::a(Yii::t('app', 'Añadir Enseñan'), ['ensenan/create'], ['class' => 'btn btn-success']) ?>
        </p>
        <!-- <div class="col-md-1"></div> -->
        <h1 class="col-md-1">Enseñan</h1>
        <div class="col-md-4"></div>
    </div>
        <?php Pjax::begin(); ?>
        <?= GridView::widget([
            'dataProvider' => $ensenan,
            'columns' => [
                // 'id',
                'color_nivel',
                'codigo_ma',
                'rol',
                [
                    'class' => ActionColumn::className(),
                    'urlCreator' => function ($action, Ensenan $model, $key, $index, $column) {
                        return Url::toRoute(["ensenan/".$action, 'id' => $model->id]);
                    }
                ],
                
            ],
            'summary' => '',
        ]); ?>
        <?php Pjax::end(); ?>
    </div>
    <div id="niveles-tab" class="tab">
    <div class="d-flex justify-content-center">
        <div class="col-md-4"></div>
        <p class="col-md-1">
            <?= Html::a(Yii::t('app', 'Añadir Nivel'), ['niveles/create'], ['class' => 'btn btn-success']) ?>
        </p>
        <!-- <div class="col-md-1"></div> -->
        <h1 class="col-md-1">Niveles</h1>
        <div class="col-md-4"></div>
    </div>
        <?php Pjax::begin(); ?>
        <?= GridView::widget([
            'dataProvider' => $niveles,
            'columns' => [
                'color',
                [
                    'class' => ActionColumn::className(),
                    'urlCreator' => function ($action, Niveles $model, $key, $index, $column) {
                        return Url::toRoute(["niveles/".$action, 'color' => $model->color]);
                    }
                ],
                
            ],
            'summary' => '',
        ]); ?>
        <?php Pjax::end(); ?>
    </div>
    <div id="telefonos-tab" class="tab">
    <div class="d-flex justify-content-center">
        <div class="col-md-4"></div>
        <p class="col-md-1">
            <?= Html::a(Yii::t('app', 'Añadir Teléfono'), ['telefonos/create'], ['class' => 'btn btn-success']) ?>
        </p>
        <!-- <div class="col-md-1"></div> -->
        <h1 class="col-md-1">Teléfonos</h1>
        <div class="col-md-4"></div>
    </div>
        <?php Pjax::begin(); ?>
        <?= GridView::widget([
            'dataProvider' => $telefonos,
            'columns' => [
                'codigo_alum',
                'telefono',
                [
                    'class' => ActionColumn::className(),
                    'urlCreator' => function ($action, Telefonos $model, $key, $index, $column) {
                        return Url::toRoute(["telefonos/".$action, 'id' => $model->id]);
                    }
                ],
                
            ],
            'summary' => '',
        ]); ?>
        <?php Pjax::end(); ?>
    </div>
    <div id="utilizan-tab" class="tab">
    <div class="d-flex justify-content-center">
        <div class="col-md-4"></div>
        <p class="col-md-1">
            <?= Html::a(Yii::t('app', 'Añadir Utilizan'), ['utilizan/create'], ['class' => 'btn btn-success']) ?>
        </p>
        <!-- <div class="col-md-1"></div> -->
        <h1 class="col-md-1">Utilizan</h1>
        <div class="col-md-4"></div>
    </div>
        <?php Pjax::begin(); ?>
        <?= GridView::widget([
            'dataProvider' => $utilizan,
            'columns' => [
                'codigo_alum',
                'codigo_ins',
                [
                    'class' => ActionColumn::className(),
                    'urlCreator' => function ($action, Utilizan $model, $key, $index, $column) {
                        return Url::toRoute(["utilizan/".$action, 'id' => $model->id]);
                    }
                ],
                
            ],
            'summary' => '',
        ]); ?>
        <?php Pjax::end(); ?>
    </div>
    <div id="instrumentos-tab" class="tab">
    <div class="d-flex justify-content-center">
        <div class="col-md-4"></div>
        <p class="col-md-1">
            <?= Html::a(Yii::t('app', 'Añadir Instrumento'), ['instrumentos/create'], ['class' => 'btn btn-success']) ?>
        </p>
        <!-- <div class="col-md-1"></div> -->
        <h1 class="col-md-1">Instrumentos</h1>
        <div class="col-md-4"></div>
    </div>
        <?php Pjax::begin(); ?>
        <?= GridView::widget([
            'dataProvider' => $instrumentos,
            'columns' => [
                // 'codigo',
                'nombre',
                [
                    'class' => ActionColumn::className(),
                    'urlCreator' => function ($action, Instrumentos $model, $key, $index, $column) {
                        return Url::toRoute(["instrumentos/".$action, 'codigo' => $model->codigo]);
                    }
                ],
                
            ],
            'summary' => '',
        ]); ?>
        <?php Pjax::end(); ?>
    </div>
<script>
        // Recuperamos todos los botones y todas las pestañas
        const tabs = document.getElementsByClassName("tab");
        const buttons = document.getElementsByClassName("boton");

        // Al principio sólo mostramos la primera tabla
        Array.from(tabs).forEach((tab, index) => {
            if (index !== 0) {
                tab.style.display = "none";
            } else {
                tab.style.display = "block";
            }
        });

        // Añadimos la funcionalidad a los botones para que hagan que se muestre la pestaña correspondiente
        Array.from(buttons).forEach((button, index) => {
            button.addEventListener("click", () => {
                Array.from(tabs).forEach((tab, tabIndex) => {
                    tab.style.display = tabIndex === index ? "block" : "none";
                });
            });
        });
</script>

views/site/error.php
<?php

/** @var yii\web\View $this */
/** @var string $name */
/** @var string $message */
/** @var Exception$exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/noticia.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\NoticiaForm */
/* @var $form yii\widgets\ActiveForm */

$this->title = 'Escribir Noticia';
?>

<div class="site-noticia-form">
    <div class="d-flex justify-content-center" style="margin-top: 1vh">
    <h1><?= Html::encode($this->title) ?></h1>
    </div>
    

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'titulo')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'texto')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'fecha')->hiddenInput()->label(false) ?>

    <?= $form->field($model, 'autora') ?>



    <div class="form-group">
        <?= Html::submitButton('Publicar', ['class' => 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>
</div>