models/Instrumentos.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "instrumentos".
 *
 * @property int $codigo
 * @property string|null $nombre
 *
 * @property Alumnos[] $codigoAlums
 * @property Pasos[] $pasos
 * @property Utilizan[] $utilizans
 */
class Instrumentos extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'instrumentos';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['nombre'], 'string', 'max' => 20],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'codigo' => 'Codigo',
            'nombre' => 'Nombre',
        ];
    }

    /**
     * Gets query for [[CodigoAlums]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getCodigoAlums()
    {
        return $this->hasMany(Alumnos::class, ['codigo' => 'codigo_alum'])->viaTable('utilizan', ['codigo_ins' => 'codigo']);
    }

    /**
     * Gets query for [[Pasos]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getPasos()
    {
        return $this->hasMany(Pasos::class, ['codigo_ins' => 'codigo']);
    }

    /**
     * Gets query for [[Utilizans]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getUtilizans()
    {
        return $this->hasMany(Utilizan::class, ['codigo_ins' => 'codigo']);
    }
}

controllers/InstrumentosController.php
<?php

namespace app\controllers;

use app\models\Instrumentos;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\Pasos;
use app\models\User;
use Yii;

/**
 * InstrumentosController implements the CRUD actions for Instrumentos model.
 */
class InstrumentosController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all Instrumentos models.
     *
     * @return string
     */
    public function actionIndex()
    {
        if (!User::canIn(['admin','maestra','alumna'])) {
            return $this->redirect('site/login');
        }
        
        $dataProvider = new ActiveDataProvider([
            'query' => Instrumentos::find(),
            /*
            'pagination' => [
                'pageSize' => 50
            ],
            'sort' => [
                'defaultOrder' => [
                    'codigo' => SORT_DESC,
                ]
            ],
            */
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Instrumentos model.
     * @param int $codigo Codigo
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($codigo)
    {
        if (!User::canIn(['admin','maestra','alumna'])) {
            return $this->redirect('site/login');
        }
        
        $pasos = new ActiveDataProvider([
            'query' => Pasos::find()->select("*")->where("codigo_ins='" . $codigo ."'")
        ]);
        return $this->render('view', [
            'model' => $this->findModel($codigo),
            'pasos' => $pasos
        ]);
    }

    /**
     * Creates a new Instrumentos model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        if (!User::canIn(['admin','maestra'])) {
            return $this->redirect('site/login');
        }
        
        $model = new Instrumentos();

        if ($this->request->isPost) {
            if ($model->load($this->request->post()) && $model->save()) {
                return $this->redirect(['view', 'codigo' => $model->codigo]);
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Instrumentos model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $codigo Codigo
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($codigo)
    {
        if (!User::canIn(['admin','maestra'])) {
            return $this->redirect('site/login');
        }

        $model = $this->findModel($codigo);

        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['view', 'codigo' => $model->codigo]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Instrumentos model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $codigo Codigo
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($codigo)
    {
        if (!User::canIn(['admin','maestra'])) {
            return $this->redirect('site/login');
        }
        
        $this->findModel($codigo)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Instrumentos model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $codigo Codigo
     * @return Instrumentos the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($codigo)
    {
        if (($model = Instrumentos::findOne(['codigo' => $codigo])) !== null) {
            return $model;
        }

        // throw new NotFoundHttpException(Yii::('app', 'The requested page does not exist.'));
    }

    public static function getNombre($codigo) {
        return Instrumentos::findOne(['codigo' => $codigo])->nombre;
    }
}

views/instrumentos/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/** @var yii\web\View $this */
/** @var app\models\Instrumentos $model */
/** @var yii\widgets\ActiveForm $form */
?>

<div class="instrumentos-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'nombre')->textInput(['maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Guardar'), ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/instrumentos/_tarjeta.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use app\models\User;
?>


<!-- <a href=<?= Url::to(['instrumentos/view', 'codigo' => $model->codigo]) ?>>
<div class="card card-instrumentos" >
    <?= Html::img('@web/imagenes/' . str_replace(" ", "_", $model->nombre)  . '.jpg', ['alt' => 'Imagen de Prueba']) ?>
    <div class="overlay">
        <div class="icon">
            <i class="fa-solid fa-arrow-right-long"></i>
        </div>
        <div class="hover-footer">
            <h3><?=$model->nombre?></h3>
        </div>
    </div>
</div>
</a> -->
<?= Html::a(
    Html::tag('div', // Encerramos el contenido en un div
        Html::img('@web/imagenes/' . str_replace(" ", "_", $model->nombre)  . '.jpg', ['alt' => 'Imagen de Prueba']) .
        '<div class="overlay">' .
            '<div class="icon">' .
                '<i class="fa-solid fa-arrow-right-long"></i>' .
            '</div>' .
            '<div class="hover-footer">' .
                '<h3>' . $model->nombre . '</h3>' .
            '</div>' .
        '</div>'
    ),
    User::linkIn(['maestra','alumna','admin'],['instrumentos/view', 'codigo' => $model->codigo],['site/login']),
    ['class' => 'card card-instrumentos']
) ?>

views/instrumentos/create.php
<?php

use yii\helpers\Html;
use app\models\User;

/** @var yii\web\View $this */
/** @var app\models\Instrumentos $model */

$this->title = Yii::t('app', 'Create Instrumentos');
?>
<div class="instrumentos-create">
    <div class="d-flex justify-content-center align-items-center">
    <p style="margin-right: 2vw; margin-top:1vh"><?= User::can('admin')?Html::a(
                '<i class="fa-solid fa-arrow-right-to-bracket"></i> ' .
                    Yii::t('app', 'Volver a administración'),
                ['site/administracion'],
                ['class' => 'btn btn-primary btn-pasos']
            ):'' ?><p>
    <h1><?= Html::encode($this->title) ?></h1>
    </div>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/instrumentos/index.php
<?php

use app\models\Instrumentos;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\ActionColumn;
use yii\grid\GridView;
use yii\widgets\Pjax;
/** @var yii\web\View $this */
/** @var yii\data\ActiveDataProvider $dataProvider */

$this->title = Yii::t('app', 'Instrumentos');
?>
<div class="instrumentos-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('app', 'Create Instrumentos'), ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php Pjax::begin(); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'codigo',
            'nombre',
            [
                'class' => ActionColumn::className(),
                'urlCreator' => function ($action, Instrumentos $model, $key, $index, $column) {
                    return Url::toRoute([$action, 'codigo' => $model->codigo]);
                 }
            ],
        ],
    ]); ?>

    <?php Pjax::end(); ?>

</div>

views/instrumentos/update.php
<?php

use yii\helpers\Html;
use app\models\User;
/** @var yii\web\View $this */
/** @var app\models\Instrumentos $model */

$this->title = Yii::t('app', 'Editar Instrumentos: {name}', [
    'name' => $model->codigo,
]);
?>
<div class="instrumentos-update">
<div class="d-flex justify-content-center align-items-center">
    <p style="margin-right: 2vw; margin-top:1vh"><?= User::can('admin')?Html::a(
                '<i class="fa-solid fa-arrow-right-to-bracket"></i> ' .
                    Yii::t('app', 'Volver a administración'),
                ['site/administracion'],
                ['class' => 'btn btn-primary btn-pasos']
            ):'' ?><p>
    <h1><?= Html::encode($this->title) ?></h1>
    </div>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/instrumentos/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\widgets\Pjax;
use yii\widgets\ListView;
use app\models\User;

/** @var yii\web\View $this */
/** @var app\models\Instrumentos $model */

$this->title = $model->nombre;
\yii\web\YiiAsset::register($this);
?>
<div class="instrumentos-view">



    <p>
        <?= User::can('admin') ? Html::a(
            '<i class="fa-solid fa-arrow-right-to-bracket"></i> ' .
                Yii::t('app', 'Volver a administración'),
            ['site/administracion'],
            ['class' => 'btn btn-primary btn-pasos']
        ) : '' ?>
        <?= User::can("maestra") ? Html::a(Yii::t('app', '<i class="fa-regular fa-pen-to-square"></i> ' . Yii::t('app', 'Actualizar')), ['update', 'codigo' => $model->codigo], ['class' => 'btn btn-primary']) : "" ?>



        <!-- <?= Html::a('<i class="fa-regular fa-trash-can"></i> ' . Yii::t('app', 'Eliminar'), ['update', 'codigo' => $model->codigo], [
                    'class' => 'btn btn-danger',
                    'data' => [
                        'confirm' => Yii::t('app', '¿Seguro que quieres eliminar este elemento?'),
                        'method' => 'post',
                    ],
                ]) ?> -->
    </p>

    <!-- <?= DetailView::widget([
                'model' => $model,
                'attributes' => [
                    'codigo',
                    'nombre',
                ],
                'options' => ['class' => ['custom-detail-view']]
            ]) ?> -->

    <?php Pjax::begin(); ?>
    <div class="d-flex justify-content-center">
        <h2 class="mb-4 mt-5"><?= $model->nombre ?></h2>
    </div>

    <?= ListView::widget([
        'dataProvider' => $pasos,
        // 'itemOptions' => ['style' => 'display: flex;'],
        'layout' => "{items}",
        'itemView' => "../pasos/_tarjeta",
        'options' => [
            'class' => 'd-flex card-prueba justify-content-center flex-wrap',
        ],
    ]); ?>

    <?php Pjax::end(); ?>

</div>